### PR TITLE
update to gnome runtime 44

### PR DESCRIPTION
**Pull request by vixalien**

### CODE REVIEW

**Comment by vixalien** [comment]
everything seems to work except when you have css, it will throw the following error in the console

image

note that I can't copy the text.

**Comment by DaPigGuy** [comment]
That was fixed here: https://github.com/sonnyp/Workbench/commit/6b0abeec4655c583a51a3ea75ecc0044df68cef3#diff-b6d66eddcd72d10dd428b0ce45dfc933f2878d911fae958dce0b63c9bdb61554

Perhaps ask for a new release to be tagged

**Comment by vixalien** [comment]
I'm pretty sure sonny will decide what to do if he sees this :) I just made this PR so I can a version that depends on GNOME 44 (I don't want to install the 600mb+ GNOME 43 runtime as well due to network and storage complications)

**Comment by sonnyp** [comment]
Please don't send PRs to the flathub. 

Everything happens on the main repo. Runtime/sdk will be updated with Workbench 44.

**Pull request closed without merging**
